--- a/Makefile	2025-08-11 19:18:11.876036991 +0900
+++ b/Makefile	2025-08-11 19:19:05.374363023 +0900
@@ -126,7 +126,7 @@
 CCAS = arm-mingw32ce-gcc
 CCASFLAGS = -g -O2
 CCDEPMODE = depmode=gcc3
-CFLAGS = -Wall -g -O -fforce-mem -fforce-addr -fthread-jumps -fcse-follow-jumps -fcse-skip-blocks -fexpensive-optimizations -fregmove -fschedule-insns2 -fstrength-reduce
+CFLAGS = -Wall -g -O -fforce-addr -fthread-jumps -fcse-follow-jumps -fcse-skip-blocks -fexpensive-optimizations -fregmove -fschedule-insns2 -fstrength-reduce
 CPP = arm-mingw32ce-gcc -E
 CPPFLAGS = 
 CXX = arm-mingw32ce-g++
